development:
  adapter: postgresql
  encoding: utf8
  database: houston_exceptions_development
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: houston_exceptions_test
  host: localhost
  prepared_statements: false
